# Generated by Django 3.2.8 on 2021-10-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acogeloApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_masc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_masc', models.CharField(max_length=50)),
                ('descripcion_larga_masc', models.TextField()),
                ('tipo_masc', models.CharField(max_length=20)),
                ('raza_masc', models.CharField(max_length=30)),
                ('edad_masc', models.CharField(max_length=30)),
                ('genero_masc', models.CharField(max_length=10)),
                ('dpto_residencia_masc', models.CharField(max_length=50)),
                ('ciudad_residencia_masc', models.CharField(max_length=50)),
                ('estado_adopcion_masc', models.CharField(max_length=15)),
                ('ruta_foto_masc', models.ImageField(max_length=200, upload_to='')),
                ('descripcion_foto_masc', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
